### ISSUE TITLE
Two players remaining

### ISSUE THREAD

**Issue by KalleJanrik** [PierreLeFevre/balls#15]
There can be two players remaning but the game still ends.

Reproduce:

3 players:
![image](https://user-images.githubusercontent.com/62420666/153484798-19182c6d-8e71-4fdb-972a-8e3cedc72eae.png)

First select ball 8
Second select ball 7
Third select ball 9

Eliminate ball 8

Then the game ends

![image](https://user-images.githubusercontent.com/62420666/153484892-da2e7926-390e-4f26-862f-53448b0eaf66.png)

**Comment by KalleJanrik** [comment]
Now 2 hours later I can't reproduce

**Comment by PierreLeFevre** [comment]
cant reproduce...
